### PR TITLE
Updated PackageReleaseNotes for vNext

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot maybe it should be v5?

**Comment by snakefoot** [comment]
Have nothing against moving from 2 to 5. If it makes it easier for users.

**Comment by snakefoot** [comment]
Could also be v4 to match Microsoft.Owin v4

**Comment by 304NotModified** [comment]
Maybe that's indeed a better idea :)

**Pull request merged**
