### PR TITLE
Log EventId to event properties

### PR DESCRIPTION
**Pull request by pysco68**
Solves #16

### CODE REVIEW

**Comment by pysco68** [comment]
@304NotModified okay for you?

**Comment by 304NotModified** [comment]
looks good to me, so merged

**Comment by 304NotModified** [comment]
@pysco68 

should this be 1.0.3 (bugfix) or 1.1 (feature)?

**Comment by 304NotModified** [comment]
I think feature, so 1.1 :)

**Comment by pysco68** [comment]
Great thank you for releasing

**Pull request merged**
