### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by 304NotModified**
Remove dead code by falling back to Debug

### CODE REVIEW

**Comment by 304NotModified** [comment]
@pysco68 

Your opinion on this change please :)

**Comment by pysco68** [comment]
Removing the code in which we shouldn't end up is certainly a good idea, however I'm not so confident with dropping the log level to "debug" by default as most Logging (NLog and others) configurations I saw up to now are not keeping that level / writing it somewhere.... thus the "danger" of having potentially important messages dropped

But you certainly have more experience in that field

**Comment by 304NotModified** [comment]
> configurations I saw up to now are not keeping that level / writing it somewhere.... thus the "danger" of having potentially important messages dropped

Well before it was 'ArgumentOutOfRangeException` instead of debug level as fallback? (in the high unlikely case)  - so we lose less messages?

**Comment by pysco68** [comment]
Sure, didn't want to say my initial implementation is really "better" but I tend to stick to the principle "let it crash" in the meaning that if something unexpected happens (some logging level that wasn't known to me at time of programming pops up) I prefer (from a DevOps POV) that the application tells it to me in the _most_ obvious way

**Comment by pysco68** [comment]
But, anyhow that was my standard policy, but I'm not forcing it. If the other way around is the standard in the NLog project I've got no problem sticking to that, I wanted just to point out that "Debug" as a target level feels weird to me; 

I'd tend to put the flags as high as possible in the case of something unexpected, that's all

**Comment by 304NotModified** [comment]
> But, anyhow that was my standard policy, but I'm not forcing it. If the other way around is the standard in the NLog project I've got no problem sticking to that, I wanted just to point out that "Debug" as a target level feels weird to me;

Thanks for the feedback @pysco68. It was easy to create an unit test with the invalid value, hence an exception isn't bad. 

superseded by https://github.com/NLog/NLog.Owin.Logging/pull/9

**Pull request closed without merging**
